import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  modalContainer: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#111111',
  },
  closeBtnText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111111',
    padding: 4,
  },
  cardSection: {
    borderWidth: 1,
    borderColor: '#E2E5E5',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    backgroundColor: '#FFFFFF',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#111111',
    marginBottom: 12,
  },
  quickBtnRow: {
    flexDirection: 'row',
    marginTop: 10,
  },
  quickBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#CED4DA',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 8,
  },
  quickBtnActive: {
    borderColor: '#FF7F00',
  },
  quickBtnText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#656C6C',
  },
  quickBtnTextActive: {
    color: '#FF7F00',
  },
  dayCircleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  dayCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1.5,
    borderColor: '#CED4DA',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  dayCircleText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#111111',
  },
  presetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  presetBtn: {
    flex: 1,
    backgroundColor: '#EFF1F5',
    borderWidth: 1,
    borderColor: '#E2E5E5',
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    marginRight: 8,
  },
  presetBtnText: {
    color: '#111111',
    fontSize: 13,
    fontWeight: 'bold',
  },
  timePickerBox: {
    borderWidth: 1,
    borderColor: '#CED4DA',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  timePickerText: {
    fontSize: 14,
    color: '#111111',
  },
  wheelPickerContainer: {
    position: 'relative',
    borderWidth: 1,
    borderColor: '#CED4DA',
    borderRadius: 12,
    marginTop: 8,
    backgroundColor: '#EFF1F5',
    alignItems: 'center',
    justifyContent: 'center',
    height: 130,
    overflow: 'hidden',
  },
  pickerFocusLineTop: {
    position: 'absolute',
    top: 42,
    left: 15,
    right: 15,
    borderTopWidth: 1.5,
    borderTopColor: '#CED4DA',
    zIndex: 1,
  },
  pickerFocusLineBottom: {
    position: 'absolute',
    bottom: 42,
    left: 15,
    right: 15,
    borderBottomWidth: 1.5,
    borderBottomColor: '#CED4DA',
    zIndex: 1,
  },
  wheelPickerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 2,
  },
  colonText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 2,
    color: '#111111',
  },
  selectBox: {
    borderWidth: 1,
    borderColor: '#CED4DA',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  selectBoxText: {
    fontSize: 14,
    color: '#111111',
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#FF7F00',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FF7F00',
  },
  actionButtonGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  actionBtn: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: '#FF7F00',
    borderRadius: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 8,
  },
  actionBtnText: {
    fontSize: 13,
    color: '#FF7F00',
    fontWeight: 'bold',
    marginLeft: 4,
  },
  saveBtn: {
    backgroundColor: '#FF7F00',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  saveBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});