import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF', padding: 20 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, marginBottom: 20 },
  titleGroup: { flexDirection: 'row', alignItems: 'center' },
  iconPill: { fontSize: 18, marginRight: 6 },
  textTitle: { color: '#333333', fontSize: 19, fontWeight: 'bold' },
  nameInput: { fontSize: 19, fontWeight: 'bold', color: '#333', borderBottomWidth: 1, borderBottomColor: '#EAEAEA', minWidth: 60, paddingVertical: 0, marginRight: 4 },
  btnClose: { padding: 5 },
  textClose: { color: '#999999', fontSize: 20 },
  cardBox: { borderWidth: 1, borderColor: '#F2F2F2', borderRadius: 12, padding: 16, marginBottom: 20, backgroundColor: '#FFFFFF' },
  label: { color: '#333333', fontSize: 15, fontWeight: 'bold', marginBottom: 12 },
  subLabel: { color: '#333333', fontSize: 13, fontWeight: 'bold', marginTop: 10, marginBottom: 8 },
  mealButtonGroup: { flexDirection: 'row', justifyContent: 'space-between' },
  mealBtn: { flex: 1, height: 44, borderWidth: 1, borderColor: '#EAEAEA', borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginHorizontal: 4 },
  mealBtnActive: { borderColor: '#FF7A00', borderWidth: 1.5 },
  mealBtnText: { color: '#666666', fontSize: 14, fontWeight: '500' },
  mealBtnTextActive: { color: '#FF7A00', fontWeight: 'bold' },
  dayCircleGroup: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  dayCircle: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, borderColor: '#EAEAEA', alignItems: 'center', justifyContent: 'center' },
  dayCircleActive: { borderColor: '#FF7A00', borderWidth: 1.5 },
  dayCircleText: { color: '#666666', fontSize: 13 },
  dayCircleTextActive: { color: '#FF7A00', fontWeight: 'bold' },
  quickDayGroup: { flexDirection: 'row', justifyContent: 'space-between' },
  quickDayBtn: { flex: 1, height: 34, backgroundColor: '#FF7A00', borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginHorizontal: 4 },
  quickDayBtnText: { color: '#FFFFFF', fontSize: 13, fontWeight: 'bold' },
  infoInputBox: { height: 44, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#EAEAEA', borderRadius: 6, paddingHorizontal: 12, marginBottom: 12 },
  infoInputText: { color: '#999999', fontSize: 13 },
  dropdownFake: { height: 44, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#EAEAEA', borderRadius: 6, paddingHorizontal: 12 },
  pickerCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#F0F0F0', borderRadius: 16, paddingHorizontal: 15, height: 140, marginBottom: 15 },
  wheel: { flex: 1, height: 120, backgroundColor: 'transparent' },
  colon: { fontSize: 16, fontWeight: 'bold', color: '#333', textAlign: 'center', width: 10 },
  voiceSettingContainer: { borderWidth: 1, borderColor: '#F2F2F2', borderRadius: 12, padding: 16, marginBottom: 25 },
  radioOption: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  radioCircle: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: '#EAEAEA', marginRight: 10 },
  radioChecked: { borderColor: '#FF7A00', backgroundColor: '#FF7A00' },
  radioText: { fontSize: 14, color: '#333', fontWeight: '500' },
  btnSave: { height: 54, backgroundColor: '#FF7A00', borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  btnSaveText: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold' },
});